version: "3"
services:
  frontend:
    container_name: "angular-test"
    build: 
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./app:/study-app
    tty: true